# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8871b9a4b8c7589d9abd6774694b9c71245d3b3f0451d3e03de2013799622e4890897971361278b9659c82c82ea9bb236ca5b9c82e33e603237d0118b7be0fd5

test:
  secret_key_base: 095cbc5bde0ddcfda74949398338bed01f284e5190e21b9743a5cd8fcfa5f954129504ef5acb774688347a4112b26e903fa19135a656c0c4210ecf91d4c3ce3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
